version: '3.2'

services:
  # Database service to set up a testing/development environment
  db:
    image: percona:8
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: policyd-rate-guard
      MYSQL_USER: policyd-rate-guard
      MYSQL_PASSWORD: Example1234
    ports:
      - 13312:3306
